version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: stockhub_db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    image: shivanandpotle/stockhub-backend:latest
    container_name: stockhub_backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/stockhub
      - JWT_SECRET=super_secret_stockhub_jwt_key_2026
      - CLIENT_URL=http://localhost
    depends_on:
      - mongodb

  frontend:
    image: shivanandpotle/stockhub-frontend:latest
    container_name: stockhub_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo-data:
